/*
 * Automatically generated by png2c
 *
 * $Id: tabthrobber.h,v 1.1 2012/05/04 21:14:10 bigfoot Exp $
 */


extern unsigned long TabThrobber[];
#define TABTHROBBER_WIDTH 225
#define TABTHROBBER_HEIGHT 15
#define TABTHROBBER_DEPTH 32
#define TABTHROBBER_IMAGES 15
