set(WebKitLegacy_INCLUDE_DIRECTORIES
    "${CMAKE_BINARY_DIR}"
    "${WEBKITLEGACY_DIR}/Storage"
    "${WEBKITLEGACY_DIR}/WebCoreSupport"
    "${CMAKE_SOURCE_DIR}/Source"
    "${FORWARDING_HEADERS_DIR}"
    "${FORWARDING_HEADERS_DIR}/WebCore"
    "${WEBCORE_DIR}/platform/linux"
    "${WEBKITLEGACY_DIR}/mui"
    "${WEBKITLEGACY_DIR}/mui/UI"
    "${WEBKITLEGACY_DIR}/mui/WebCoreSupport"
    "${WEBKITLEGACY_DIR}/mui/Widgets"
    "${WEBKITLEGACY_DIR}/mui/Plugins"
    "${WEBKITLEGACY_DIR}/Storage"
    "${WEBKITLEGACY_DIR}/WebCoreSupport"
    "${WEBKITLEGACY_DIR}/mui/UI/AROS/include/"
)

list(APPEND WebKitLegacy_SOURCES
    mui/UI/addressbargroupclass.cpp
    mui/UI/appclass.cpp
    mui/UI/aros_stuff.c
    mui/UI/asl.cpp
    mui/UI/AutofillBackingStore.cpp
    mui/UI/AutofillManager.cpp
    mui/UI/autofillpopupclass.cpp
    mui/UI/autofillpopuplistclass.cpp
    mui/UI/blockmanagergroupclass.cpp
    mui/UI/blockmanagerlistclass.cpp
    mui/UI/blockmanagerwindowclass.cpp
    mui/UI/bookmarkgroupclass.cpp
    mui/UI/bookmarklisttreeclass.cpp
    mui/UI/bookmarkpanelgroupclass.cpp
    mui/UI/bookmarkwindowclass.cpp
    mui/UI/cattmp.cpp
    mui/UI/classes.cpp
    mui/UI/clipboard.cpp
    mui/UI/ColorChooserController.cpp
    mui/UI/colorchooserpopupclass.cpp
    mui/UI/consolelistclass.cpp
    mui/UI/consolewindowclass.cpp
    mui/UI/contextmenugroupclass.cpp
    mui/UI/contextmenulistclass.cpp
    mui/UI/cookiemanagerlistclass.cpp
    mui/UI/cookiemanagergroupclass.cpp
    mui/UI/cookiemanagerlistclass.cpp
    mui/UI/cookiemanagerwindowclass.cpp
    mui/UI/choosetitlegroupclass.cpp
    mui/UI/datetimechooserpopupclass.cpp
    mui/UI/DateTimeChooserController.cpp
    mui/UI/DownloadDelegateMorphOS.cpp
    mui/UI/downloadgroupclass.cpp
    mui/UI/downloadlistclass.cpp
    mui/UI/downloadwindowclass.cpp
    mui/UI/faviconclass.cpp
    mui/UI/findtextclass.cpp
    mui/UI/historybuttonclass.cpp
    mui/UI/historylistclass.cpp
    mui/UI/historylisttreeclass.cpp
    mui/UI/historypanelgroupclass.cpp
    mui/UI/historypopstringclass.cpp
    mui/UI/iconclass.cpp
    mui/UI/icufiles.cpp
    mui/UI/linklistclass.cpp
    mui/UI/locale.cpp
    mui/UI/loginwindowclass.cpp
    mui/UI/mediacontrolsgroupclass.cpp
    mui/UI/menuclass.cpp
    mui/UI/menuitemclass.cpp
    mui/UI/methodstack.c
    mui/UI/mimetypegroupclass.cpp
    mui/UI/mimetypelistclass.cpp
    mui/UI/mui.cpp
    mui/UI/navigationgroupclass.cpp
    mui/UI/networkledsgroupclass.cpp
    mui/UI/networklistclass.cpp
    mui/UI/networkwindowclass.cpp
    mui/UI/owbbrowserclass.cpp
    mui/UI/owbwindowclass.cpp
    mui/UI/passwordmanagergroupclass.cpp
    mui/UI/passwordmanagerlistclass.cpp
    mui/UI/passwordmanagerwindowclass.cpp
    mui/UI/popstringclass.cpp
    mui/UI/prefswindowclass.cpp
    mui/UI/owbgroupclass.cpp
    mui/UI/printerwindowclass.cpp
    mui/UI/quicklinkbuttongroupclass.cpp
    mui/UI/quicklinkgroupclass.cpp
    mui/UI/quicklinkparentgroupclass.cpp
    mui/UI/scriptmanagergroupclass.cpp
    mui/UI/scriptmanagerhostlistclass.cpp
    mui/UI/scriptmanagerlistclass.cpp
    mui/UI/scriptmanagerwindowclass.cpp
    mui/UI/seeksliderclass.cpp
    mui/UI/spacerclass.cpp
    mui/UI/searchbargroupclass.cpp
    mui/UI/searchmanagergroupclass.cpp
    mui/UI/searchmanagerlistclass.cpp
    mui/UI/searchmanagerwindowclass.cpp
    mui/UI/splashwindowclass.cpp
    mui/UI/suggestlistclass.cpp
    mui/UI/suggestpopstringclass.cpp
    mui/UI/tabthrobber.cpp
    mui/UI/tabtransferanimclass.cpp
    mui/UI/throbber.cpp
    mui/UI/titleclass.cpp
    mui/UI/titlelabelclass.cpp
    mui/UI/toolbutton_addbookmarkclass.cpp
    mui/UI/toolbutton_bookmarksclass.cpp
    mui/UI/toolbuttonclass.cpp
    mui/UI/toolbutton_newtabclass.cpp
    mui/UI/TopSitesManager.cpp
    mui/UI/transferanimclass.cpp
    mui/UI/urlprefsgroupclass.cpp
    mui/UI/urlprefslistclass.cpp
    mui/UI/urlprefswindowclass.cpp
    mui/UI/urlstringclass.cpp
    mui/UI/utils.cpp
    mui/UI/volumesliderclass.cpp
    mui/UI/WebViewPrivate.cpp

    mui/BackForwardList.cpp
    mui/DefaultPolicyDelegate.cpp
    mui/DOMCoreClasses.cpp
    mui/DOMCSSClasses.cpp
    mui/DOMEventsClasses.cpp
    mui/DOMHTMLClasses.cpp
    mui/DOMRange.cpp
    mui/HTTPHeaderPropertyBag.cpp
    mui/WebApplicationCache.cpp
    mui/WebBackForwardList.cpp
    mui/WebDatabaseManager.cpp
    mui/WebDataSource.cpp
    mui/WebDragData.cpp
    mui/WebDocumentLoader.cpp
    mui/WebDownload.cpp
    mui/WebError.cpp
    mui/WebFramePolicyListener.cpp
    mui/WebGeolocationPosition.cpp
    mui/WebIconDatabase.cpp
    mui/WebHistory.cpp
    mui/WebHistoryItem.cpp
    mui/WebHitTestResults.cpp
    mui/WebInspector.cpp
    mui/WebMutableURLRequest.cpp
    mui/WebNavigationAction.cpp
    mui/WebPasswordFormData.cpp
    mui/WebPasswordFormUtils.cpp
    mui/WebPreferences.cpp
    mui/WebResource.cpp
    mui/WebScriptObject.cpp
    mui/WebSecurityOrigin.cpp
    mui/WebFrame.cpp
    mui/WebUtils.cpp
    mui/WebView.cpp
    mui/WebURLResponse.cpp

    mui/Plugins/npapi.cpp
    mui/Plugins/PluginDatabase.cpp
    mui/Plugins/PluginDatabaseMUI.cpp
    mui/Plugins/PluginDataMorphOS.cpp
    mui/Plugins/PluginMainThreadScheduler.cpp
    mui/Plugins/PluginPackage.cpp
    mui/Plugins/PluginPackageMorphOS.cpp
    mui/Plugins/PluginStream.cpp
    mui/Plugins/PluginView.cpp
    mui/Plugins/PluginViewMorphOS.cpp

    mui/WebCoreSupport/WebChromeClient.cpp
    mui/WebCoreSupport/WebContextMenuClient.cpp
    mui/WebCoreSupport/WebDesktopNotificationsDelegate.cpp
    mui/WebCoreSupport/WebDragClient.cpp
    mui/WebCoreSupport/WebEditorClient.cpp
    mui/WebCoreSupport/WebGeolocationClient.cpp
    mui/WebCoreSupport/WebFrameLoaderClient.cpp
    mui/WebCoreSupport/WebFrameNetworkingContext.cpp
    mui/WebCoreSupport/WebInspectorClient.cpp
    mui/WebCoreSupport/WebPlatformStrategies.cpp
    mui/WebCoreSupport/WebPluginInfoProvider.cpp
    mui/WebCoreSupport/WebProgressTrackerClient.cpp
    mui/WebCoreSupport/WebVisitedLinkStore.cpp

    mui/Widgets/WebDragDataMorphOS.cpp

    Storage/StorageAreaImpl.cpp
    Storage/StorageAreaSync.cpp
    Storage/StorageNamespaceImpl.cpp
    Storage/StorageSyncManager.cpp
    Storage/StorageThread.cpp
    Storage/StorageTracker.cpp
    Storage/WebDatabaseProvider.cpp
    Storage/WebStorageNamespaceProvider.cpp

    WebCoreSupport/WebViewGroup.cpp
)

set(WebKitLegacy_LIBRARY_TYPE STATIC)
