/*
 * Automatically generated by png2c
 *
 * $Id: throbber.h,v 1.1 2012/05/04 21:14:10 bigfoot Exp $
 */


extern unsigned long Throbber[];
#define THROBBER_WIDTH 336
#define THROBBER_HEIGHT 21
#define THROBBER_DEPTH 32
#define THROBBER_IMAGES 16

