application: webkit-queues
version: 178455 # SVN revision of last major change
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- remote_api: on

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: main.py
